server:
  port: 7777
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: oa-token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 3600
  # token风格
  token-style: random-32
  # 是否尝试从 header 里读取 Token
  is-read-head: true
  # 是否开启自动续签
  auto-renew: true
  # 临时有效期，单位s，例如将其配置为 1800 (30分钟)，代表用户如果30分钟无操作，则此Token会立即过期
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时同端互斥)
  is-concurrent: true
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 10s
spring:
  web:
    resources:
      static-locations: file:/${uploadPath}
  mvc:
    static-path-pattern: /oa/upload/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://192.168.211.21:3306/oa?useUnicode=true&&characterEncoding=utf-8&&useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zretc.oa.entity
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
uploadPath: D:/resource/